server:
  port: 8081
spring:
  application:
    name: pw-land-and-exploitation
#----------------------------------------
# Open API
#----------------------------------------
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'

#----------------------------------------
# Camunda
#----------------------------------------
camunda:
  bpm:
    client:
      base-url: http://localhost:8080/engine-rest
    deployment:
      processes:
        - name: Land and exploitation process
          tenant: MEX
          bpmnResourcePattern: classpath*:processmodels/*.bpmn
          dmnResourcePattern: classpath*:processmodels/*.dmn
          formResourcePattern: classpath*:processmodels/*.form
  worker:
    max:
      retries: 3
    retry:
      timeout: 10

#----------------------------------------
# Camunda integration settings
#----------------------------------------
# Rest client
integration:
  camunda:
    connectTimeout: 5
    readTimeout: 20
    url: http://localhost:8080/engine-rest