spring:
  application:
    name: pw-land-and-exploitation
  security:
    oauth2:
      client:
        provider:
          casedata:
            token-uri: ${config.casedata.token-uri}
        registration:
          casedata:
            authorization-grant-type: client_credentials
            provider: casedata
            client-id: ${config.casedata.client-id}
            client-secret: ${config.casedata.client-secret}

#----------------------------------------
# Open API
#----------------------------------------
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'

#----------------------------------------
# Camunda
#----------------------------------------
camunda:
  bpm:
    client:
      base-url: ${config.camunda.base-url}
      disable-backoff-strategy: true
      async-response-timeout: 15000
    deployment:
      processes:
        - name: Land and exploitation process
          tenant: MEX
          bpmnResourcePattern: classpath*:processmodels/*.bpmn
          dmnResourcePattern: classpath*:processmodels/*.dmn
          formResourcePattern: classpath*:processmodels/*.form
  worker:
    max:
      retries: 3
    retry:
      timeout: 10

#----------------------------------------
# Integration settings
#----------------------------------------
integration:
  camunda:
    connectTimeout: 5
    readTimeout: 20
    url: ${config.camunda.base-url}
  casedata:
    connectTimeout: 5
    readTimeout: 20
    url: ${config.casedata.base-url}
    