#========================================
# Integration test specific settings
#========================================
#----------------------------------------
# Camunda
#----------------------------------------

camunda:
  bpm:
    client:
      base-url: http://replaced_by_test:8080
  
#----------------------------------------
# Camunda integration settings
#----------------------------------------
# Rest client
integration:
  camunda:
    connectTimeout: 5
    readTimeout: 20
    url: http://replaced_by_test:8080
